# Generated by Django 3.0.3 on 2020-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
