# Generated by Django 3.0.3 on 2020-03-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_originprob_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originprob',
            name='category',
            field=models.CharField(blank=True, choices=[('programmers', 'Programmers'), ('baekjoon', 'BaekJoon'), ('swea', 'SWEA')], max_length=255, null=True),
        ),
    ]
