# Generated by Django 3.0.3 on 2020-03-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200311_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_code',
        ),
    ]
