# Generated by Django 3.0.3 on 2020-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
