# Generated by Django 3.0.3 on 2020-03-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_commentlike_solutionlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionlike',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='solutionlike',
            name='solution',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='SolutionLike',
        ),
    ]
