# Generated by Django 3.0.3 on 2020-03-06 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solutions', '0005_auto_20200306_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solution',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='solution_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
