# Generated by Django 3.0.5 on 2020-04-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_subcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
