# Generated by Django 3.0.5 on 2020-06-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_auto_20200405_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-created_at']},
        ),
    ]
