# Generated by Django 3.0.5 on 2020-05-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='creator',
            new_name='by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
